[supabase]
url = "https://qppotvdhplujczuaxcid.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwcG90dmRocGx1amN6dWF4Y2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDUxNjksImV4cCI6MjA2MTQyMTE2OX0.CwpOichnksU2AfEr8kLNAs48beMRpuFc8dnA2gv3ND0"
